services:
  - type: web
    name: justcallbud
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: true
    autoDeploy: true
    healthCheckPath: /health