services:
  - type: web
    name: just-call-bud
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: MODAL_TOKEN_ID
        sync: false
      - key: MODAL_TOKEN_SECRET
        sync: false