name: Modal Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal requests huggingface-hub
          pip install langchain langchain_core transformers torch accelerate
          
      - name: Deploy to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          python -m modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
          python -m modal deploy modal_functions.py
          
      - name: Test deployment
        run: |
          sleep 10  # Wait for deployment to be ready
          curl -X POST https://rriggin--just-call-bud-prod--chat.modal.run/chat \
            -H "Content-Type: application/json" \
            -d '{"prompt_text": "How do I fix a leaky faucet?", "history": []}'
          
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Triggering Render deployment..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST $RENDER_DEPLOY_HOOK)
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n 1)
          BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "Render response: $BODY"
          echo "HTTP status: $HTTP_STATUS"
          
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Render deployment trigger failed with status $HTTP_STATUS"
            echo "Response: $BODY"
            exit 1
          fi
          
          echo "Render deployment triggered successfully"
          
          # Wait for deployment to start
          echo "Waiting for deployment to start..."
          sleep 30